idf_component_register(
    SRCS "main.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "demo_display.c"
         "demo_button.c"
         "demo_audio.c"
         "demo_battery.c"
         "demo_radio.c"
         "demo_wifi.c"
         "demo_ble.c"
         "demo_low_power.c"
         "tracker_engine.c"
         "tracker_wifi_spy.c"
         "tracker_ble_scanner.c"
         "tracker_alarm.c"
         "tracker_ui.c"
         "tracker_power.c"
         "cosmic_sonar.c"
         "cosmic_quiet_scout.c"
         "cosmic_orbit_weather.c"
         "cosmic_sos_beacon.c"
         "cosmic_power.c"
         "cosmic_ui.c"
         "lv_font_cn_16.c"
    INCLUDE_DIRS "."
    REQUIRES bsp bt esp_event esp_hw_support esp_netif esp_timer esp_wifi nvs_flash
)
